from __future__ import annotations

import json
import os
from pathlib import Path

import streamlit as st
from azure.storage.blob import BlobServiceClient

LOCAL_QUALITY_REPORT_DIR = Path("data/quality/reports")
REMOTE_QUALITY_REPORT_PREFIX = "quality/reports"

LOCAL_QUALITY_SUMMARY_PATH = LOCAL_QUALITY_REPORT_DIR / "latest_quality_summary.json"


def get_blob_connection_string() -> str | None:
    """
    Read Azure Storage connection string from Streamlit secrets or environment.

    The dashboard only reads generated validation artifacts. It does not run validation
    checks or modify pipeline outputs.
    """
    try:
        value = st.secrets.get("AZURE_STORAGE_CONNECTION_STRING")
        if value:
            return str(value)
    except Exception:
        pass

    return os.getenv("AZURE_STORAGE_CONNECTION_STRING")


def get_blob_container_name() -> str | None:
    """
    Read Azure Blob container name from Streamlit secrets or environment.

    AZURE_BLOB_CONTAINER is used by the existing upload workflow.
    AZURE_STORAGE_CONTAINER_NAME is kept as a compatible fallback.
    """
    for key in ["AZURE_BLOB_CONTAINER", "AZURE_STORAGE_CONTAINER_NAME"]:
        try:
            value = st.secrets.get(key)
            if value:
                return str(value)
        except Exception:
            pass

        value = os.getenv(key)
        if value:
            return value

    return None


@st.cache_data(ttl=300, show_spinner=False)
def load_json_from_blob(blob_name: str) -> dict | None:
    """
    Load one JSON artifact from Azure Blob Storage.

    Returns None if Blob configuration is unavailable or the artifact cannot be read.
    The caller can then fall back to local files.
    """
    connection_string = get_blob_connection_string()
    container_name = get_blob_container_name()

    if not connection_string or not container_name:
        return None

    try:
        blob_service_client = BlobServiceClient.from_connection_string(
            connection_string
        )
        blob_client = blob_service_client.get_blob_client(
            container=container_name,
            blob=blob_name,
        )
        raw_data = blob_client.download_blob().readall()
        return json.loads(raw_data.decode("utf-8"))
    except Exception:
        return None


def load_json_from_local(path: Path) -> dict | None:
    """Load one local JSON artifact if available"""
    if not path.exists():
        return None

    try:
        with path.open("r", encoding="utf-8") as file:
            return json.load(file)
    except Exception:
        return None


def load_quality_report_artifact(filename: str) -> dict | None:
    """
    Load a generated quality report artifact.

    Read order:
    1. Azure Blob Storage: quality/reports/<filename>
    2. Local fallback: data/quality/reports/<filename>

    This keeps the deployed dashboard connected to scheduled Container Apps Job
    outputs while preserving local development support.
    """
    remote_blob_name = f"{REMOTE_QUALITY_REPORT_PREFIX}/{filename}"
    local_path = LOCAL_QUALITY_REPORT_DIR / filename

    blob_report = load_json_from_blob(remote_blob_name)
    if blob_report is not None:
        return blob_report

    return load_json_from_local(local_path)


def load_quality_summary(path: Path = LOCAL_QUALITY_SUMMARY_PATH) -> dict | None:
    """
    Load the latest pipeline quality summary as a read-only dashboard artifact.

    The dashboard does not execute validation checks. It only displays the
    latest summary generated by the scheduled refresh / quality check workflow.
    """
    if path == LOCAL_QUALITY_SUMMARY_PATH:
        return load_quality_report_artifact("latest_quality_summary.json")

    return load_json_from_local(path)


def render_quality_summary(summary: dict | None) -> None:
    """
    Render a compact read-only quality summary.

    This is a dashboard-facing summary of the latest generated quality report,
    not a live validation runner.
    """
    if summary is None:
        st.info(
            "No validation summary is available yet. "
            "Run the quality check workflow to generate the latest summary."
        )
        return

    status = summary.get("status", "unknown")
    total_checks = summary.get("total_checks", 0)
    passed = summary.get("passed", 0)
    warnings = summary.get("warnings", 0)
    failed = summary.get("failed", 0)
    ingest_time = summary.get("ingest_time", "unknown")
    source = summary.get("source", "unknown")

    if status == "passed":
        st.success("Validation result: passed")
    elif status == "passed_with_warnings":
        st.warning("Validation result: passed with warnings")
    elif status == "failed":
        st.error("Validation result: failed")
    else:
        st.info(f"Validation result: {status}")

    st.caption(
        f"Checks: {total_checks} total · {passed} passed · "
        f"{warnings} warnings · {failed} failed"
    )

    st.caption(f"Source: {source} · Last validation time: {ingest_time}")
    st.caption("Open the Data Quality page for dataset-level and check-level details.")
