#!/usr/bin/env bash
set -euo pipefail

DBT_TARGET="${DBT_TARGET:-prod}"
DBT_DATASET="${DBT_DATASET:-olist}"
DBT_LOCATION="${DBT_LOCATION:-EU}"
DBT_THREADS="${DBT_THREADS:-4}"

export DBT_TARGET
export DBT_DATASET
export DBT_LOCATION
export DBT_THREADS

CONTROL_ATTEMPT_ID="${CONTROL_ATTEMPT_ID:-}"
CONTROL_WINDOW_START="${CONTROL_WINDOW_START:-}"
CONTROL_WINDOW_END="${CONTROL_WINDOW_END:-}"

DBT_WINDOW_ARGS=()

if [[ -n "${CONTROL_WINDOW_START}" \
   || -n "${CONTROL_WINDOW_END}" ]]; then

  if [[ -z "${CONTROL_WINDOW_START}" \
     || -z "${CONTROL_WINDOW_END}" ]]; then
    echo "ERROR: CONTROL_WINDOW_START and CONTROL_WINDOW_END must both be set."
    exit 1
  fi

  if [[ -z "${CONTROL_ATTEMPT_ID}" ]]; then
    echo "ERROR: CONTROL_ATTEMPT_ID is required in governed window mode."
    exit 1
  fi

  DBT_WINDOW_VARS="$(
    printf \
      '{"control_window_start":"%s","control_window_end":"%s"}' \
      "${CONTROL_WINDOW_START}" \
      "${CONTROL_WINDOW_END}"
  )"

  DBT_WINDOW_ARGS=(
    --vars
    "${DBT_WINDOW_VARS}"
  )

  echo "Running in governed window mode."
  echo "Window start: ${CONTROL_WINDOW_START}"
  echo "Window end:   ${CONTROL_WINDOW_END}"
else
  echo "No control window supplied."
  echo "Running in full-history compatibility mode."
fi

if [ -z "${DBT_PROJECT_ID:-}" ]; then
  echo "ERROR: DBT_PROJECT_ID environment variable is required."
  exit 1
fi

if [ ! -f "profiles.yml.template" ]; then
  echo "ERROR: profiles.yml.template was not found in the current working directory."
  exit 1
fi

echo "Starting Olist dbt pipeline..."
echo "Current working directory: $(pwd)"
echo "Using dbt target: ${DBT_TARGET}"
echo "Using BigQuery project: ${DBT_PROJECT_ID}"
echo "Using default dbt dataset: ${DBT_DATASET}"
echo "Using BigQuery location: ${DBT_LOCATION}"
echo "Using dbt threads: ${DBT_THREADS}"

echo "Generating dbt profiles.yml from runtime environment..."
envsubst < profiles.yml.template > profiles.yml

echo "dbt version:"
dbt --version

if [ -f "packages.yml" ]; then
  echo "packages.yml found. Installing dbt packages..."
  dbt deps
else
  echo "No packages.yml found. Skipping dbt deps."
fi

echo "Validating dbt connection..."
dbt debug --target "${DBT_TARGET}"

echo "Running dbt build..."
dbt build \
  --target "${DBT_TARGET}" \
  "${DBT_WINDOW_ARGS[@]}"

echo "Validating dbt build artifacts..."

if [ ! -f "target/manifest.json" ]; then
  echo "ERROR: target/manifest.json was not generated by dbt build."
  exit 1
fi

if [ ! -f "target/run_results.json" ]; then
  echo "ERROR: target/run_results.json was not generated by dbt build."
  exit 1
fi

# Preserve artifacts generated by `dbt build`.
#
# The build run_results.json contains the actual pipeline execution results
# for models and tests, including statuses, failures, and runtimes.
#
# `dbt docs generate` is used only to create catalog.json. However, it also
# regenerates manifest.json and run_results.json. Those docs-generation
# artifacts must not replace the build artifacts used by monitoring.
ARTIFACT_BACKUP_DIR="$(mktemp -d)"

cleanup_artifact_backup() {
  rm -rf "${ARTIFACT_BACKUP_DIR}"
}

trap cleanup_artifact_backup EXIT

echo "Preserving dbt build artifacts..."
cp target/manifest.json "${ARTIFACT_BACKUP_DIR}/manifest.json"
cp target/run_results.json "${ARTIFACT_BACKUP_DIR}/run_results.json"

echo "Generating dbt catalog metadata..."
dbt docs generate \
  --target "${DBT_TARGET}" \
  "${DBT_WINDOW_ARGS[@]}"

if [ ! -f "target/catalog.json" ]; then
  echo "ERROR: target/catalog.json was not generated by dbt docs generate."
  exit 1
fi

# Restore the original build artifacts while keeping the newly generated
# catalog.json. The monitoring loader therefore reads:
#
# - manifest.json from dbt build
# - run_results.json from dbt build
# - catalog.json from dbt docs generate
echo "Restoring dbt build artifacts..."
cp "${ARTIFACT_BACKUP_DIR}/manifest.json" target/manifest.json
cp "${ARTIFACT_BACKUP_DIR}/run_results.json" target/run_results.json

if [ ! -f "monitoring/load_artifacts_to_bigquery.py" ]; then
  echo "ERROR: monitoring/load_artifacts_to_bigquery.py was not found."
  exit 1
fi

echo "Loading dbt artifacts into BigQuery monitoring tables..."

# Reuse the dbt project ID for monitoring unless GCP_PROJECT_ID is explicitly
# configured separately at runtime.
export GCP_PROJECT_ID="${GCP_PROJECT_ID:-${DBT_PROJECT_ID}}"

# Explicitly expose the dbt target directory to the artifact parser.
export DBT_ARTIFACT_DIR="${DBT_ARTIFACT_DIR:-$(pwd)/target}"

# Configure the monitoring destination and pipeline identity.
# Each value remains overridable through the Cloud Run Job environment.
export MONITORING_DATASET_ID="${MONITORING_DATASET_ID:-olist_monitoring}"
export MONITORING_JOB_NAME="${MONITORING_JOB_NAME:-olist-dbt-build-job}"
export MONITORING_ENVIRONMENT="${MONITORING_ENVIRONMENT:-${DBT_TARGET}}"

python monitoring/load_artifacts_to_bigquery.py

# In governed mode, resolve the monitoring run created by M8 from the exact
# M10 control attempt, then run M9 against that exact monitoring_run_id.
# Compatibility-mode runs without CONTROL_ATTEMPT_ID keep the existing M8-only
# behavior rather than guessing the latest monitoring run.
if [[ -n "${CONTROL_ATTEMPT_ID}" ]]; then
  if [ ! -f "monitoring/resolve_monitoring_run.py" ]; then
    echo "ERROR: monitoring/resolve_monitoring_run.py was not found."
    exit 1
  fi

  if [ ! -f "monitoring/reviewer/run_status_review.py" ]; then
    echo "ERROR: monitoring/reviewer/run_status_review.py was not found."
    exit 1
  fi

  echo "Resolving exact monitoring run for control attempt..."

  MONITORING_RUN_ID="$(
    python monitoring/resolve_monitoring_run.py \
      --project-id "${GCP_PROJECT_ID}" \
      --dataset-id "${MONITORING_DATASET_ID}" \
      --location "${DBT_LOCATION}" \
      --control-attempt-id "${CONTROL_ATTEMPT_ID}"
  )"

  if [[ -z "${MONITORING_RUN_ID}" ]]; then
    echo "ERROR: monitoring_run_id resolution returned an empty value."
    exit 1
  fi

  echo "Resolved monitoring_run_id: ${MONITORING_RUN_ID}"

  M9_REVIEW_OUTPUT_PATH="${M9_REVIEW_OUTPUT_PATH:-/tmp/m9_review_${MONITORING_RUN_ID}.json}"

  echo "Running M9 exact-run deterministic review..."

  python monitoring/reviewer/run_status_review.py \
    --monitoring-run-id "${MONITORING_RUN_ID}" \
    --project-id "${GCP_PROJECT_ID}" \
    --dataset-id "${MONITORING_DATASET_ID}" \
    --job-name "${MONITORING_JOB_NAME}" \
    --environment "${MONITORING_ENVIRONMENT}" \
    > "${M9_REVIEW_OUTPUT_PATH}"

  echo "M9 review completed successfully."
  echo "M9 review output: ${M9_REVIEW_OUTPUT_PATH}"

  if [ ! -f "monitoring/reviewer/persist_review_to_bigquery.py" ]; then
    echo "ERROR: monitoring/reviewer/persist_review_to_bigquery.py was not found."
    exit 1
  fi

  echo "Persisting deterministic M9 review..."

  python monitoring/reviewer/persist_review_to_bigquery.py \
    --review-json "${M9_REVIEW_OUTPUT_PATH}" \
    --project-id "${GCP_PROJECT_ID}" \
    --dataset-id "${MONITORING_DATASET_ID}" \
    --location "${DBT_LOCATION}"

  echo "M9 deterministic review persisted successfully."
else
  echo "No CONTROL_ATTEMPT_ID supplied."
  echo "Skipping exact-run M9 review in compatibility mode."
fi

echo "Olist dbt pipeline and metadata refresh completed successfully."
