# ------------------------------------------------
# BigQuery Upload
# ------------------------------------------------
bigquery_config:
  project_id: balmy-nuance-468118-g4
  dataset: nyc_taxi
  table: yellow_tripdata_cleaned
  summary_table: trip_summary_hourly

# ------------------------------------------------
# GeoJSON Config
# ------------------------------------------------
geojson_url: "external/taxi_zones.geojson"