# ------------------------------------------------
# BigQuery Upload
# ------------------------------------------------
bigquery_config:
  project_id: precise-antenna-461516-u3
  dataset: nyc_taxi
  table: yellow_tripdata_cleaned
  summary_table: trip_summary_hourly

# ------------------------------------------------
# GeoJSON Config
# ------------------------------------------------
geojson_url: "external/taxi_zones.geojson"